# Microsoft Fabric SQL Analytics Endpoint - SQL Query in Notebook Examples

## Example 1: Running a Simple SQL Query in a Notebook

### **Step 1: Open a New Notebook**
1. Navigate to **Microsoft Fabric**.
2. Click on **Notebooks** and select **New SQL Notebook**.

### **Step 2: SQL Analytics Endpoint Status**

In [2]:

SELECT 'Connected to SQL Analytics Endpoint' AS Status;

## Example 2: Query Employee Details in a Notebook

In [3]:
SELECT empno, ename, job, sal, deptno FROM emp ORDER BY sal DESC;

## Example 3: Joining Tables to Analyze Salaries

In [4]:
SELECT e.ename, e.job, e.sal, d.dname, d.loc
FROM emp e
JOIN dept d ON e.deptno = d.deptno
ORDER BY e.sal DESC;

## Example 4: Using Aggregation in a Notebook

In [7]:
SELECT d.dname, AVG(e.sal) AS avg_salary
FROM emp e
JOIN dept d ON e.deptno = d.deptno
GROUP BY d.dname;